///
/// @file flir_timestamp_calculator.hpp
/// @author zheming.lyu (zheming.lyu@wayz.ai)
/// @brief Header of class FlirTimestampCalculator and its helper classes
/// @version 0.1
/// @date 2019-11-08
///
/// @copyright Copyright 2018 Wayz.ai. All Rights Reserved.
///

#pragma once
#include <cstdint>

namespace wayz {
namespace hera {
namespace device {
namespace camera {
namespace flir {

///
/// @brief A helper class for converting timestamp
///
/// It converts raw-embedded-timestamp got from FLIR SDK to standard timestamp
///
class FlirEmbeddedTimestamp {
public:
    ///
    /// @brief Construct a new Flir Embedded Timestamp object
    ///
    /// @param rawdata raw uint32_t typed embedded-timestamp got from FLIR SDK
    explicit FlirEmbeddedTimestamp(uint32_t rawdata);

    ///
    /// @brief Implicitly cast to us
    ///
    /// @return int64_t timestamp from the start of a 128s cycle, in us
    /// @note The result is not UTC time
    int64_t get_us() const;

    ///
    /// @brief Implicitly cast to ns
    ///
    /// @return int64_t timestamp from the start of a 128s cycle, in us
    /// @note The result is not UTC time
    int64_t get_ns() const;

private:
    int64_t time_in_cycle_us_;  ///< timestamp from the start of a 128s cycle, in us
};

///
/// @brief A helper class for converting shutter duration
///
/// It converts raw-embedded-shutter got from FLIR SDK to standard shutter duration,
///
class FlirEmbeddedShutter {
public:
    ///
    /// @brief Construct a new Flir Embedded Shutter object
    ///
    /// @param rawdata raw uint32_t typed embedded-shutter got from FLIR SDK
    explicit FlirEmbeddedShutter(uint32_t rawdata);

    ///
    /// @brief Implicitly cast to us
    ///
    /// @return int64_t shutter duration, in us
    int64_t get_us() const;

    ///
    /// @brief Implicitly cast to ns
    ///
    /// @return int64_t shutter duration, in us
    int64_t get_ns() const;

private:
    ///
    /// @brief Granularity of embbedded shutter of FLIR Camera, in us
    ///
    /// @note This may various by different Camera Models and Camera Modes
    /// @todo Find the relationship of exact value
    /// @note This value 19us, is for Mode 1 of 23S6C
    static constexpr int32_t ShutterStepUs_ = 19;

    int64_t duration_us_;  ///< shutter duration, in us
};

///
/// @brief Calculate intrinsic timestamp of FLIR camera's image
///
/// Wayz Automony Confluence Page:
/// @anchor cam-sync
/// <a href="https://confluence.newayz.com/pages/viewpage.action?pageId=7220639"
/// target="_blank" rel="noopener noreferrer">
/// Principle of Tron Sync Board</a> section: Camera
class FlirTimestampCalculator final {
public:
    ///
    /// @brief Construct a new Flir Timestamp Calculator object
    ///
    FlirTimestampCalculator();
    FlirTimestampCalculator(const FlirTimestampCalculator&) = delete;
    FlirTimestampCalculator& operator=(const FlirTimestampCalculator&) = delete;

    ///
    /// @brief Get the intrinsic timestamp
    ///
    /// @param [out] out the calculation result, intrinsic timestamp, in ns, if calculation succeed,
    /// otherwise a nonsensical value
    /// @param time_received_ns the timestamp on image received
    /// @param embedded_timestamp embedded_timestamp of image
    /// @param embedded_shutter embedded_timestamp of shutter
    /// @return true calculation succeed
    /// @return false calculation failed
    /// @note Caller must check the return value,
    /// since the result is nonsensical if calculation failed
    /// @note You are not supposed to completely understand calculation here,
    /// by only reading this document generated by doxygen.
    /// @see @ref cam-sync "Principle of Tron Sync Board"
    bool get_intrinsic_time(int64_t& out,
                            const int64_t time_received_ns,
                            const FlirEmbeddedTimestamp& embedded_timestamp,
                            const FlirEmbeddedShutter& embedded_shutter);

private:
    ///
    /// @brief Frequency of camera image, in frame per second
    ///
    /// Identical to Tron Sync Board's frequency of camera trigger

    static constexpr int32_t Fps_ = 10;

    ///
    /// @brief Period of camera image, in us
    ///
    static constexpr int64_t PeriodUs_ = 1'000'000LL / Fps_;

    ///
    /// @brief Period of camera image, in ns
    ///
    static constexpr int64_t PeriodNs_ = 1'000'000'000LL / Fps_;

    ///
    /// @brief Time shiftation of first trigger in a sync-cycle
    /// from it origin time, in us
    ///
    /// 20ms
    /// @see @ref cam-sync "Principle of Tron Sync Board"
    static constexpr int64_t ShiftationUs_ = -20'000;

    ///
    /// @brief Tolerance of time shiftation detection
    ///
    /// 5ms
    static constexpr int64_t ShiftationToleranceUs_ = 5'000;

    ///
    /// @brief Cycle of FLIR embedded timestamp, in us
    ///
    /// 128s
    /// @see FLIR SDK
    static constexpr int64_t EmbeddedTimestampCycleUs_ = 128'000'000LL;

    ///
    /// @brief Cycle of Sync, in us
    ///
    /// 3s
    /// @see @ref cam-sync "Principle of Tron Sync Board"
    static constexpr int64_t SyncCycleNs_ = 3 * 1'000'000'000LL;

    ///
    /// @brief Upper limit of interval duration of a shifted trigger
    ///
    static constexpr int64_t MaxMatchedIntervalUs_ = PeriodUs_ + ShiftationUs_ + ShiftationToleranceUs_;

    ///
    /// @brief Lower limit of interval duration of a shifted trigger
    ///
    static constexpr int64_t MinMatchedIntervalUs_ = PeriodUs_ + ShiftationUs_ - ShiftationToleranceUs_;

private:
    ///
    /// @brief Check if interval is a valid shifted interval
    ///
    /// @param us interval duration to check
    /// @return true valid
    /// @return false invalid
    bool check_match(int64_t us);

    ///
    /// @brief embbeded timestamp of Camera of last frame
    ///
    /// Ranged [0, EmbeddedTimestampCycleUs_), in us
    int64_t last_embedded_timestamp_us_;

    ///
    /// @brief accumulated cycle of embbeded timestamp
    ///
    /// An integer multiple of EmbeddedTimestampCycleUs_, in us
    int64_t accumulated_cycle_us_;

    ///
    /// @brief intrinsic timestamp last frame, UTC, in us
    ///
    /// This value is only valid if calculation succeed for last frame,
    /// and it used for escaped duration from last frame
    int64_t last_intrinsic_time_us_;

    ///
    /// @brief last synced timestamp's multipler timestamp
    ///
    /// time of last aligned tick at integer multiple of
    // SyncCycleNs_, in times of SyncCycleNs_;
    /// @see @ref cam-sync "Principle of Tron Sync Board"
    int64_t last_sync_time_multipler_;

    ///
    /// @brief frame count from last aligned tick
    ///
    int64_t frame_count_;

    ///
    /// @brief whether valid calculation done in history
    ///
    bool inited;
};

}  // namespace flir
}  // namespace camera
}  // namespace device
}  // namespace hera
}  // namespace wayz