///
/// @file xsens_timestamp_calculator.hpp
/// @author zheming.lyu (zheming.lyu@wayz.ai)
/// @brief
/// @version 0.1
/// @date 2021-09-07
///
/// @copyright Copyright 2018 Wayz.ai. All Rights Reserved.
///

#pragma once

#include <cstdint>

#include "common/include/logger/logger.hpp"
#include "common/include/utils/time.hpp"

namespace wayz {
namespace hera {
namespace device {
namespace imu {
namespace xsens {

///
/// @brief Calculate intrinsic timestamp of Xsens data
///
/// Using same sync trigger of camera
///
/// Wayz Automony Confluence Page:
/// @anchor xsens-sync
/// <a href="https://confluence.newayz.com/pages/viewpage.action?pageId=7220639"
/// target="_blank" rel="noopener noreferrer">
/// Principle of Tron Sync Board</a> section: Xsens
class TimestampCalculator final {
public:
    ///
    /// @brief Construct a new Timestamp Calculator object
    ///
    TimestampCalculator()
    {
        set_fps(DefaultFps_);
    }
    TimestampCalculator(const TimestampCalculator&) = delete;
    TimestampCalculator& operator=(const TimestampCalculator&) = delete;

    ///
    /// @brief Set Fps of Camera
    ///
    /// @param fps
    /// @note must be same with real fps
    void set_fps(const int32_t fps)
    {
        Fps_ = fps;
        PeriodNs_ = time::OneSecond / fps;
        MaxMatchedIntervalNs_ = PeriodNs_ + ShiftationNs_ + ShiftationToleranceNs_;
        MinMatchedIntervalNs_ = PeriodNs_ + ShiftationNs_ - ShiftationToleranceNs_;
    }

    ///
    /// @brief Get the intrinsic timestamp
    ///
    /// @param [out] out_timestamp, out the calculation result, intrinsic timestamp, in ns, if calculation succeed,
    /// otherwise a nonsensical value
    /// @param time_received_ns, the timestamp on image received
    /// @param xsens_tick, local xsens_tick in 10kHz
    /// @param trigger_indicated, is sync bit of trigger indicate on, from xsens packet
    ///
    /// @return true calculation succeed
    /// @return false calculation failed
    ///
    /// @note Caller must check the return value,
    /// since the result is nonsensical if calculation failed
    /// @note You are not supposed to completely understand calculation here,
    /// by only reading this document generated by doxygen.
    /// @see @ref xsens-sync "Principle of Tron Sync Board"
    bool get_intrinsic_time(int64_t& out_timestamp,
                            const int64_t time_received_ns,
                            const uint32_t xsens_tick,
                            const bool trigger_indicated)
    {
        if (last_tick_ > xsens_tick) {
            accumulated_ticks_ += 0x1'0000'0000;
        }
        last_tick_ = xsens_tick;

        int64_t local_time = accumulated_ticks_ + (int64_t)(xsens_tick)*TickToNs_;
        if (trigger_indicated) {
            int64_t escaped_time = local_time - last_xsens_local_timestamp_ns_;
            last_xsens_local_timestamp_ns_ = local_time;

            if (check_match(escaped_time)) {
                int64_t global_time = (time_received_ns / SyncCycleNs_) * SyncCycleNs_ + PeriodNs_ + ShiftationNs_;

                auto& T2 = global_time;
                auto& T1 = last_matched_global_time_;
                auto& t2 = local_time;
                auto& t1 = last_matched_local_time_;

                if (step_ == 0) {
                    log::info << "Xsens:: first check match succeed" << log::endl;
                    step_ = 1;
                } else {
                    int64_t dt1 = t2 - t1;
                    int64_t dT1 = T2 - T1;

                    if (step_ == 1) {
                        log::info << "Xsens:: second check match succeed" << log::endl;
                        tr_ = t2;
                        td_ = T2 - t2;
                        k_ = 1;
                        step_ = 2;
                    } else {
                        int64_t td_est = T1 + (t2 - t1) * k_ - t2;
                        int64_t td_truth = T2 - t2;
                        int64_t td_err = td_truth - td_est;
                        if (td_err > TdShiftMax) {
                            td_err = TdShiftMax;
                        } else if (td_err < -TdShiftMax) {
                            td_err = -TdShiftMax;
                        }

                        double k_truth = double(T2 - T1) / double(t2 - t1);
                        double k_err = (k_truth - k_) / k_;
                        if (k_err > KShiftMax) {
                            k_err = KShiftMax;
                        } else if (k_err < -KShiftMax) {
                            k_err = -KShiftMax;
                        }

                        tr_ = t2;
                        td_ = td_est + td_err;
                        k_ = k_ + k_err * k_;
                    }
                }

                last_matched_local_time_ = local_time;
                last_matched_global_time_ = global_time;
            }
        }

        if (step_ < 2) {
            return false;
        } else {
            out_timestamp = td_ + k_ * double(local_time - tr_) + tr_;
            return true;
        }
    }

private:
    bool check_match(int64_t escaped_time)
    {
        return (escaped_time < MaxMatchedIntervalNs_ && escaped_time > MinMatchedIntervalNs_);
    }

private:
    ///
    /// @brief Time shiftation of first trigger in a sync-cycle
    /// from it origin time, in us
    ///
    /// 20ms
    /// @see @ref xsens-sync "Principle of Tron Sync Board"
    static constexpr int64_t ShiftationNs_ = -20'000'000;

    ///
    /// @brief Tolerance of time shiftation detection
    ///
    /// 5ms
    static constexpr int64_t ShiftationToleranceNs_ = 5'000'000;

    ///
    /// @brief Cycle of Sync, in us
    ///
    /// 3s
    /// @see @ref cam-sync "Principle of Tron Sync Board"
    static constexpr int64_t SyncCycleNs_ = 3 * 1'000'000'000LL;

    ///
    /// @brief Xsens tick period in ns
    ///
    static constexpr int64_t TickToNs_ = time::OneSecond / 10'000;

    static constexpr int64_t TdShiftMax = 100'000;              // ns
    static constexpr const double KShiftMax = 1.0 / 1000000.0;  // ppm


private:
    ///
    /// @brief Default Fps
    ///
    int32_t DefaultFps_ = 10;

    ///
    /// @brief Frequency of trigger, in frame per second
    ///
    /// Identical to Tron Sync Board's frequency of camera trigger
    int32_t Fps_;

    ///
    /// @brief Period of camera image, in ns
    ///
    int64_t PeriodNs_;

    ///
    /// @brief Upper limit of interval duration of a shifted trigger
    ///
    int64_t MaxMatchedIntervalNs_;

    ///
    /// @brief Lower limit of interval duration of a shifted trigger
    ///
    int64_t MinMatchedIntervalNs_;


private:
    uint32_t last_tick_{0};
    int64_t accumulated_ticks_{0};
    int64_t last_xsens_local_timestamp_ns_{0};

    int64_t last_matched_local_time_{0};
    int64_t last_matched_global_time_{0};

    int32_t step_{0};
    double k_{1};
    int64_t tr_{0};
    int64_t td_{0};
};

}  // namespace xsens
}  // namespace imu
}  // namespace device
}  // namespace hera
}  // namespace wayz