///
/// @file image.cpp
/// @author zheming.lyu (zheming.lyu@wayz.ai)
/// @brief Header of class Image and class ImageDeviceData
/// @version 0.1
/// @date 2020-04-13
///
/// @copyright Copyright 2018 Wayz.ai. All Rights Reserved.
///

#pragma once

#include "data/dummy_data.hpp"
#include "device.hpp"

namespace wayz {
namespace hera {
namespace device {
namespace dummy {
namespace image {

#pragma pack(push, 1)

///
/// @brief Device data for dummy::Image, Derived from Storage Data
///
class ImageData final : public data::DeviceData {
public:
    ImageData() = delete;

public:
    ///
    /// @brief Data structure of dummy::Image packet
    ///
    /// The packet is generated by dummy code
    ///
    struct ImageDataUnion {
        int32_t image_width;
        int32_t image_height;
    };

    ///
    /// @brief Union to allow access by data or by bytes
    ///
    union {
        ImageDataUnion data;                  ///< union entry: data with structure
        uint8_t buf[sizeof(ImageDataUnion)];  ///< union entry: raw buffer of bytes
    };
};

#pragma pack(pop)

///
/// @brief A dummy device foobar, for sample, Derived from Device
///
class Image final : public Device {
public:
    ///
    /// @brief Construct a new Velodyne object
    ///
    /// @note pass DummyRate and DummyValue as essential parameters
    /// @see Device::Device()
    Image(const uint32_t id,
          const std::string& vendor_type,
          const std::string& name,
          const bool forward,
          ipc::IPCQueue<data::SensorData>* const ipc_queue,
          storage::StorageManager* const storage) :
        Device(id, vendor_type, name, forward, ipc_queue, storage, HistoryDepth_, EssentialParameterTypes)
    {}
    Image& operator=(const Image&) = delete;

    ///
    /// @brief Destroy the Image object
    ///
    /// calls Device::stop()
    virtual ~Image()
    {
        stop();
    }

#ifdef WITH_DRIVER
    virtual HeraErrno connect() override;

    virtual void disconnect() override;

    virtual data::DeviceDataPtr fetch() override;

    virtual HeraErrno adjust_parameter(const std::string& type, const std::string& value) override;
#endif

    virtual data::SensorDataPtr convert(data::DeviceDataPtr& storage_data) override
    {
        return do_convert(storage_data);
    }

    ///
    /// @brief Static convert function for read / convert / replay
    ///
    static data::SensorDataPtr do_convert(data::DeviceDataPtr& storage_data);

public:
    static const std::vector<std::string> EssentialParameterTypes;  ///< Essential Parameters for device

    static const std::vector<std::string> OptionalParameterTypes;  ///< Optional Parameters for device

private:
    static constexpr size_t HistoryDepth_ = 1;  ///< History Depth, 1

    int64_t period_us_;  ///< period on which dummy device return a new data, in us
};

}  // namespace image
}  // namespace dummy
}  // namespace device
}  // namespace hera
}  // namespace wayz