HERA_PLUGIN_DATA_DEFINE_START(ImageData, 0x0102)
///
/// @brief Data structure of dummy::Image packet
///
/// The packet is generated by dummy code
///
struct ImageDataUnion {
    int32_t image_width;
    int32_t image_height;
};

///
/// @brief Union to allow access by data or by bytes
///
union {
    ImageDataUnion data;                  ///< union entry: data with structure
    uint8_t buf[sizeof(ImageDataUnion)];  ///< union entry: raw buffer of bytes
};
HERA_PLUGIN_DATA_DEFINE_END