/// 
/// @file plugin_data.hpp
/// @author lyu zheming (zheming.lyu@wayz.ai)
/// @brief 
/// @date 2020-08-19
/// 
/// @copyright Copyright 2018 Wayz.ai. All Rights Reserved.
/// 

#pragma once

#include "data/dummy_data.hpp"

namespace wayz {
namespace hera {
namespace device {
namespace dummy {
namespace image {

#pragma pack(push, 1)

///
/// @brief Device data for dummy::Image, Derived from Storage Data
///
class ImageData final : public data::DeviceData {
public:
    ImageData() = delete;

public:
    ///
    /// @brief Data structure of dummy::Image packet
    ///
    /// The packet is generated by dummy code
    ///
    struct ImageDataUnion {
        int32_t image_width;
        int32_t image_height;
    };

    ///
    /// @brief Union to allow access by data or by bytes
    ///
    union {
        ImageDataUnion data;                  ///< union entry: data with structure
        uint8_t buf[sizeof(ImageDataUnion)];  ///< union entry: raw buffer of bytes
    };
};

#pragma pack(pop)

}  // namespace foobar
}  // namespace dummy
}  // namespace device
}  // namespace hera
}  // namespace wayz