HERA_PLUGIN_DATA_DEFINE_START(FoobarData, 0x0101)
///
/// @brief Data structure of dummy::Foobar packet
///
/// The packet is generated by dummy code
///
struct FoobarDataUnion {
    int32_t int_value;               ///< a dummy int value
    int8_t char_value[4];            ///< a dummy char array with fixed length
    uint32_t string_message_length;  ///< length of string_message
    uint8_t string_message[0];       ///< a variable-length buffer
};

///
/// @brief Union to allow access by data or by bytes
///
union {
    FoobarDataUnion data;                  ///< union entry: data with structure
    uint8_t buf[sizeof(FoobarDataUnion)];  ///< union entry: raw buffer of bytes
};

HERA_PLUGIN_DATA_DEFINE_END
