/// 
/// @file plugin_data.hpp
/// @author lyu zheming (zheming.lyu@wayz.ai)
/// @brief 
/// @date 2020-08-19
/// 
/// @copyright Copyright 2018 Wayz.ai. All Rights Reserved.
/// 

#pragma once

#include "data/dummy_data.hpp"

namespace wayz {
namespace hera {
namespace device {
namespace dummy {
namespace foobar {

#pragma pack(push, 1)

///
/// @brief Device data for dummy::Foobar, Derived from Storage Data
///
class FoobarData final : public data::DeviceData {
public:
    FoobarData() = delete;

public:
    ///
    /// @brief Data structure of dummy::Foobar packet
    ///
    /// The packet is generated by dummy code
    ///
    struct FoobarDataUnion {
        int32_t int_value;               ///< a dummy int value
        int8_t char_value[4];            ///< a dummy char array with fixed length
        uint32_t string_message_length;  ///< length of string_message
        uint8_t string_message[0];       ///< a variable-length buffer
    };

    ///
    /// @brief Union to allow access by data or by bytes
    ///
    union {
        FoobarDataUnion data;                  ///< union entry: data with structure
        uint8_t buf[sizeof(FoobarDataUnion)];  ///< union entry: raw buffer of bytes
    };
};

#pragma pack(pop)

}  // namespace foobar
}  // namespace dummy
}  // namespace device
}  // namespace hera
}  // namespace wayz