#include <fstream>
#include <iostream>
#include <regex>
#include <sstream>
#include <string>
#include <vector>

#include "common/include/third_party/json.hpp"
#include "generator.hpp"

namespace wayz {
namespace hera {
namespace device {
namespace parameter {

bool output(const std::string& output_filename,
            const std::string& escaped_file_content,
            const std::vector<ParamDef>& param_defs,
            const std::string& category_name,
            const std::string& vendor_name)
{
    std::ofstream output_file;
    output_file.open(output_filename, std::ios::out);
    output_file << R"(
///
/// @brief Generated by hera-parameter-generator
///
)";
    output_file << escaped_file_content;

    output_file << R"(
#pragma once

#include "common/include/third_party/enum.hpp"
#include "device/include/parameter.hpp"

namespace wayz {
namespace hera {
namespace device {    
)";

    output_file << "namespace " << category_name << " {\n";
    output_file << "namespace " << vendor_name << " {\n";

    for (auto& param : param_defs) {
        if (param.category == ParamDef::Enum) {
            output_file << "\nBETTER_ENUM(" << param.type << ", int32_t, " << param.options << ");\n";
        }
    }

    output_file << R"(
class LocalParameters : public ParametersInterface {
public:
    LocalParameters()
    {
)";

    for (auto& param : param_defs) {
        if (param.category == ParamDef::Numeric) {
            output_file << "        set_" << param.designator << "(" << param.default_value << ");\n";
        } else {
            output_file << "        set_" << param.designator << "(\"" << param.default_value << "\");\n";
        }
    }
    output_file << R"R(    }

private:
    static bool m_to_bool(const std::string& str) {
        if (str.empty()) {
            return false;
        } else if (str[0] == 'F' || str[0] == 'f' || str[0] == '0') {
            return false;
        } else {
            return true;
        }
    } 

public:
    std::string rules() const override {
        return static_rules();
    }

    static std::string static_rules() {
        return R"RR()R";

    nlohmann::json rules = nlohmann::json::array();
    for (auto& param : param_defs) {
        nlohmann::json param_json = nlohmann::json::object();
        switch (param.category) {
        case ParamDef::Boolean: {
            param_json["type"] = "boolean";
            param_json["name"] = param.designator;
            param_json["defaultValue"] = param.default_value;
            param_json["comment"] = param.comment;
            param_json["mutable"] = param.is_mutable;
            param_json["requirement"] = param.requirement;
            rules.push_back(param_json);
        } break;
        case ParamDef::Enum: {
            param_json["type"] = "enum";
            param_json["name"] = param.designator;

            auto raw_options = param.options;
            raw_options.erase(std::remove_if(raw_options.begin(), raw_options.end(), isspace), raw_options.end());
            std::stringstream ss(raw_options);
            std::string options = "[ ";
            std::string token;
            while (getline(ss, token, ',')) {
                options += '"' + token + "\", ";
            }
            options.erase(options.end() - 2, options.end());
            options += " ]";

            param_json["options"] = nlohmann::json::parse(options);
            param_json["defaultValue"] = param.default_value;
            param_json["comment"] = param.comment;
            param_json["mutable"] = param.is_mutable;
            param_json["requirement"] = param.requirement;
            rules.push_back(param_json);
        } break;
        case ParamDef::Numeric: {
            param_json["type"] = param.type;
            param_json["name"] = param.designator;
            param_json["range"] = nlohmann::json::object();
            param_json["range"]["min"] = param.range_min;
            param_json["range"]["max"] = param.range_max;
            param_json["range"]["step"] = param.range_step;
            param_json["defaultValue"] = param.default_value;
            param_json["comment"] = param.comment;
            param_json["mutable"] = param.is_mutable;
            param_json["requirement"] = param.requirement;
            rules.push_back(param_json);
        } break;
        case ParamDef::String: {
            param_json["type"] = "string";
            param_json["name"] = param.designator;
            param_json["regex"] = param.regex;
            param_json["defaultValue"] = param.default_value;
            param_json["comment"] = param.comment;
            param_json["mutable"] = param.is_mutable;
            param_json["requirement"] = param.requirement;
            rules.push_back(param_json);
        } break;
        default:
            break;
        }
    }

    output_file << rules.dump() << R"R()RR";
    }

public:
    bool set(const nlohmann::json& json_input) override
    {
        bool good = true;
)R";
    for (auto& param : param_defs) {
        output_file << "        good &= set_" << param.designator << "(json_input[\"" << param.designator
                    << "\"].get<std::string>());\n";
    }
    output_file << R"(
        return good;
    }

    bool set(const std::string& type, const std::string& value) override
    {
)";
    for (auto& param : param_defs) {
        output_file << "        if (type == \"" << param.designator << "\") { return set_" << param.designator
                    << "(value);}\n";
    }
    output_file << "        return false;\n    }\n";

    for (auto& param : param_defs) {
        // clang-format off
    output_file << R"(
public:
    )" << param.type << R"( get_)" << param.designator << R"(() const noexcept
    {
        return m_)" << param.designator << R"(;
    }

    bool set_)" << param.designator << R"((const )" << param.type << R"(& value)
    {
        json_values_[")" << param.designator << R"("] = )";
        if (param.category == ParamDef::Enum) {
            output_file << "value._to_string();";
        } else {
            output_file << "value;";
        }
        output_file << R"(
        m_)" << param.designator << R"( = value;
        return true;
    }
)";

    if (param.category == ParamDef::Numeric) {
        std::string func = "std::stoll";
        if (param.type == "double") {
            func = "std::stod";
        }
        output_file << R"(
    bool set_)" << param.designator << R"((const std::string& value)
    {
        try {
            )" << param.type << R"( t_value = )" << func << R"((value);
            set_)" << param.designator << R"((t_value);
            return true;
        } catch (std::exception& e) {
            return false;
        }
    }
)";
    } else if (param.category == ParamDef::Enum) {
         output_file << R"(
    bool set_)" << param.designator << R"((const std::string& value)
    {
        auto t_value = )" << param.type << R"(::_from_string_nocase_nothrow(value.c_str());
        if (t_value) {
            set_)" << param.designator << R"((*t_value);
            return true;
        } else {
            return false;
        }
    }
)";
    } else if (param.category == ParamDef::Boolean) {
        output_file << R"(
    bool set_)" << param.designator << R"((const std::string& value)
    {
        try {
            )" << param.type << R"( t_value = m_to_bool(value);
            set_)" << param.designator << R"((t_value);
            return true;
        } catch (std::exception& e) {
            return false;
        }
    }
)";
    }

    if (param.category == ParamDef::Enum) {
        output_file << R"(
private:
    )" << param.type << R"( m_)" << param.designator << R"({)" << param.type << R"(::)" << param.default_value << R"(};

)";
    } else {
        output_file << R"(
private:
    )" << param.type << R"( m_)" << param.designator << R"({};
)";
    }
        // clang-format on
    }

    output_file << R"(
};

)";
    output_file << "}  // namespace " << category_name << "\n";
    output_file << "}  // namespace " << vendor_name << "\n";

    output_file << R"(}  // namespace device
}  // namespace parameter
}  // namespace device
)";

    return true;
}  // namespace hera

}  // namespace parameter
}  // namespace device
}  // namespace hera
}  // namespace wayz