#include <algorithm>
#include <fstream>
#include <iostream>
#include <regex>
#include <sstream>
#include <string>
#include <vector>

#include "common/include/third_party/json.hpp"
#include "generator.hpp"

namespace wayz {
namespace hera {
namespace device {
namespace parameter {

void replace_all(std::string& data, std::string toSearch, std::string replaceStr)
{
    size_t pos = data.find(toSearch);
    while (pos != std::string::npos) {
        data.replace(pos, toSearch.size(), replaceStr);
        pos = data.find(toSearch, pos + replaceStr.size());
    }
}

bool output(const std::string& output_filename,
            const std::string& escaped_file_content,
            const DeviceDesc& device_desc,
            const std::string& category_name,
            const std::string& vendor_name,
            const std::string& sub_name)
{
    std::ofstream output_file;
    output_file.open(output_filename, std::ios::out);
    output_file << R"(
///
/// @brief Generated by hera-parameter-generator
///
)";
    output_file << escaped_file_content;

    output_file << R"(
#pragma once

#include "common/include/third_party/enum.hpp"
#include "device/include/parameter.hpp"

namespace wayz {
namespace hera {
namespace device {    
)";

    output_file << "namespace " << category_name << " {\n";
    output_file << "namespace " << vendor_name << " {\n";

    if (!sub_name.empty()) {
        output_file << "namespace " << sub_name << " {\n";
    }

    for (auto& param : device_desc.parameters) {
        if (param.category == ParamDef::Enum) {
            output_file << "\nBETTER_ENUM(" << param.type << ", int32_t, " << param.options << ");\n";
        }
    }

    output_file << R"(
class LocalParameters : public ParametersInterface {
public:
    LocalParameters()
    {
)";

    for (auto& param : device_desc.parameters) {
        if (param.category == ParamDef::Numeric || param.category == ParamDef::Boolean) {
            output_file << "        set_" << param.designator << "(" << param.default_value << ");\n";
        } else {
            output_file << "        set_" << param.designator << "(\"" << param.default_value << "\");\n";
        }
    }
    output_file << R"R(    }

private:
    static bool m_to_bool(const std::string& str) {
        if (str.empty()) {
            return false;
        } else if (str[0] == 'T' || str[0] == 't' || str[0] == '1') {
            return true;
        } else {
            return false;
        }
    }

public:
    bool exist_type(const std::string& type) const override {
)R";

    for (auto& param : device_desc.parameters) {
        output_file << "        if (type == \"" << param.designator << "\") { return true; }\n";
    };
    output_file << "        return false;";

    output_file << R"R(
    }

public:
    std::string description() const override {
        return static_description;
    }

    static std::string static_description;

    std::string plain_rules() const override {
        return static_plain_rules;
    }

    static std::string static_plain_rules;

public:
    bool set(const nlohmann::json& json_input) override
    {
        bool good = true;
)R";
    for (auto& param : device_desc.parameters) {
        output_file << "        try { set_" << param.designator << "(json_input.at(\"" << param.designator << "\").get<std::string>()); } catch (std::exception& e) { good = false; }\n";
    }
    output_file << R"(
        return good;
    }

    bool set(const std::string& type, const std::string& value) override
    {
)";
    for (auto& param : device_desc.parameters) {
        output_file << "        if (type == \"" << param.designator << "\") { return set_" << param.designator
                    << "(value);}\n";
    }
    output_file << "        return false;\n    }\n";

    for (auto& param : device_desc.parameters) {
        // clang-format off
    output_file << R"(
public:
    )" << param.type << R"( get_)" << param.designator << R"(() const noexcept
    {
        return m_)" << param.designator << R"(;
    }

    bool set_)" << param.designator << R"((const )" << param.type << R"(& value)
    {
        json_values_[")" << param.designator << R"("] = )";
        if (param.category == ParamDef::Enum) {
            output_file << "value._to_string();";
        } else {
            output_file << "value;";
        }
        output_file << R"(
        m_)" << param.designator << R"( = value;
        return true;
    }
)";

    if (param.category == ParamDef::Numeric) {
        std::string func = "std::stoll";
        if (param.type == "double") {
            func = "std::stod";
        }
        output_file << R"(
    bool set_)" << param.designator << R"((const std::string& value)
    {
        try {
            )" << param.type << R"( t_value = )" << func << R"((value);
            set_)" << param.designator << R"((t_value);
            return true;
        } catch (std::exception& e) {
            return false;
        }
    }
)";
    } else if (param.category == ParamDef::Enum) {
         output_file << R"(
    bool set_)" << param.designator << R"((const std::string& value)
    {
        auto t_value = )" << param.type << R"(::_from_string_nocase_nothrow(value.c_str());
        if (t_value) {
            set_)" << param.designator << R"((*t_value);
            return true;
        } else {
            return false;
        }
    }
)";
    } else if (param.category == ParamDef::Boolean) {
        output_file << R"(
    bool set_)" << param.designator << R"((const std::string& value)
    {
        try {
            )" << param.type << R"( t_value = m_to_bool(value);
            set_)" << param.designator << R"((t_value);
            return true;
        } catch (std::exception& e) {
            return false;
        }
    }
)";
    }

    if (param.category == ParamDef::Enum) {
        output_file << R"(
private:
    )" << param.type << R"( m_)" << param.designator << R"({)" << param.type << R"(::)" << param.default_value << R"(};

)";
    } else {
        output_file << R"(
private:
    )" << param.type << R"( m_)" << param.designator << R"({};
)";
    }
        // clang-format on
    }

    output_file << R"R(
};

std::string LocalParameters::static_description = R"RR()R";

    nlohmann::json rules = nlohmann::json::array();
    std::string plain_rules;
    for (auto& param : device_desc.parameters) {
        nlohmann::json param_json = nlohmann::json::object();
        std::string comment_tabed = param.comment;
        replace_all(comment_tabed, "\n", "\n   ");
        switch (param.category) {
        case ParamDef::Boolean: {
            if (!param.is_convert) {
                param_json["type"] = "boolean";
                param_json["label"] = param.label;
                param_json["name"] = param.designator;
                param_json["defaultValue"] = param.default_value;
                param_json["comment"] = param.comment;
                param_json["mutable"] = param.is_mutable;
                param_json["requirement"] = param.requirement;
                rules.push_back(param_json);
            } else {
                plain_rules += "\n";
                plain_rules +=
                        " - " + param.designator + ": " + "boolean" + "\n   default = " + param.default_value + "\n";
                plain_rules += "   " + comment_tabed + "\n";
            }
        } break;
        case ParamDef::Enum: {
            if (!param.is_convert) {
                param_json["type"] = "enum";
                param_json["label"] = param.label;
                param_json["name"] = param.designator;

                auto raw_options = param.options;
                raw_options.erase(std::remove_if(raw_options.begin(), raw_options.end(), isspace), raw_options.end());
                std::stringstream ss(raw_options);
                std::string options = "[ ";
                std::string token;
                while (getline(ss, token, ',')) {
                    options += '"' + token + "\", ";
                }
                options.erase(options.end() - 2, options.end());
                options += " ]";

                param_json["options"] = nlohmann::json::parse(options);
                param_json["defaultValue"] = param.default_value;
                param_json["comment"] = param.comment;
                param_json["mutable"] = param.is_mutable;
                param_json["requirement"] = param.requirement;
                rules.push_back(param_json);
            } else {
                plain_rules += "\n";
                plain_rules +=
                        " - " + param.designator + ": " + "enum" + "\n   default = " + param.default_value + "\n";
                plain_rules += "   options: " + param.options + "\n";
                plain_rules += "   " + comment_tabed + "\n";
            }
        } break;
        case ParamDef::Numeric: {
            if (!param.is_convert) {
                param_json["type"] = param.type;
                param_json["label"] = param.label;
                param_json["name"] = param.designator;
                param_json["range"] = nlohmann::json::object();
                param_json["range"]["min"] = param.range_min;
                param_json["range"]["max"] = param.range_max;
                param_json["range"]["step"] = param.range_step;
                param_json["defaultValue"] = param.default_value;
                param_json["comment"] = param.comment;
                param_json["mutable"] = param.is_mutable;
                param_json["requirement"] = param.requirement;
                rules.push_back(param_json);
            } else {
                plain_rules += "\n";
                plain_rules +=
                        " - " + param.designator + ": " + param.type + "\n   default = " + param.default_value + "\n";
                plain_rules += "   min: " + param.range_min + " max: " + param.range_max + "\n";
                plain_rules += "   " + comment_tabed + "\n";
            }
        } break;
        case ParamDef::String: {
            if (!param.is_convert) {
                param_json["type"] = "string";
                param_json["label"] = param.label;
                param_json["name"] = param.designator;
                param_json["regex"] = param.regex;
                param_json["defaultValue"] = param.default_value;
                param_json["comment"] = param.comment;
                param_json["mutable"] = param.is_mutable;
                param_json["requirement"] = param.requirement;
                rules.push_back(param_json);
            } else {
                plain_rules += "\n";
                plain_rules +=
                        " - " + param.designator + ": " + "string" + "\n   default = " + param.default_value + "\n";
                plain_rules += "   regex: " + param.regex + "\n";
                plain_rules += "   " + comment_tabed + "\n";
            }
        } break;
        default:
            break;
        }
    }

    nlohmann::json desc = nlohmann::json::object();
    desc["parameters"] = rules;
    desc["label"] = device_desc.label;
    desc["comment"] = device_desc.comment;

    output_file << desc.dump() << ")RR\";\n\n";

    output_file << "std::string LocalParameters::static_plain_rules = R\"RR(";
    output_file << plain_rules << ")RR\";\n\n";

    if (!sub_name.empty()) {
        output_file << "}  // namespace " << sub_name << "\n";
    }
    output_file << "}  // namespace " << category_name << "\n";
    output_file << "}  // namespace " << vendor_name << "\n";

    output_file << R"(}  // namespace device
}  // namespace parameter
}  // namespace device
)";

    return true;
}  // namespace hera

}  // namespace parameter
}  // namespace device
}  // namespace hera
}  // namespace wayz