///
/// @file foobar.hpp
/// @author zheming.lyu (zheming.lyu@wayz.ai)
/// @brief Header of class Foobar and class FoobarStorageData
/// @version 0.1
/// @date 2019-11-07
///
/// @copyright Copyright 2018 Wayz.ai. All Rights Reserved.
///

#pragma once

#include "../../device.hpp"
#include "../dummy_data.hpp"

namespace wayz {
namespace hera {
namespace dummy {

#pragma pack(push, 1)

///
/// @brief Storage data for dummy::Foobar, Derived from Storage Data
///
class FoobarStorageData final : public StorageData {
public:
    FoobarStorageData() = delete;

public:
    ///
    /// @brief Data structure of dummy::Foobar packet
    ///
    /// The packet is generated by dummy code
    ///
    struct FoobarRawData {
        int32_t int_value;               ///< a dummy int value
        int8_t char_value[4];            ///< a dummy char array with fixed length
        uint32_t string_message_length;  ///< length of string_message
        uint8_t string_message[0];       ///< a variable-length buffer
    };

    ///
    /// @brief Union to allow access by data or by bytes
    ///
    union {
        FoobarRawData data;                  ///< union entry: data with structure
        uint8_t buf[sizeof(FoobarRawData)];  ///< union entry: raw buffer of bytes
    };
};

#pragma pack(pop)

///
/// @brief A dummy device foobar, for sample, Derived from Device
///
class Foobar final : public Device {
public:
    ///
    /// @brief Construct a new Velodyne object
    ///
    /// @note pass DummyRate and DummyValue as essential parameters
    /// @see Device::Device()
    Foobar(DeviceIdType id,
           const std::string& type,
           const std::string& name,
           const std::string& folder,
           bool read_mode) :
        Device(id, type, name, folder, read_mode, {DeviceParameterType::DummyRate, DeviceParameterType::DummyValue})
    {}
    Foobar(const Foobar&) = delete;
    Foobar& operator=(const Foobar&) = delete;

    ///
    /// @brief Destroy the Aceinna object
    ///
    /// calls Device::stop()
    virtual ~Foobar()
    {
        stop();
    }


    virtual HeraErrno connect() override;

    virtual void disconnect() override;

    virtual StorageDataPtr fetch() override;

    virtual SensorDataPtr convert(StorageDataPtr&& storage_data) override;

    virtual HeraErrno adjust_parameter(DeviceParameterType type, const std::string& value) override;

private:
    int64_t period_us_;           ///< period on which dummy device return a new data, in us
    int32_t int_value_;           ///< the int value to fill storage data
    std::string string_message_;  ///< the string message to fill storage data

    static const std::string DefaultMessage_;  ///< Default value of string message
};

}  // namespace dummy
}  // namespace hera
}  // namespace wayz