# Host Name
name = "Tron"

# Directory to store record files
data_directory = "/var/hera/data"

# File of setting
setting_file = "/var/hera/setting.json"

# Directory to search and load plugins
plugin_directory = {
  # Load device-plugins from
  device = "/usr/local/lib/hera/plugin"
  # Load upload-plugins from
  upload = "/usr/local/lib/hera/plugin"
}

# Log file Mode
log = {
  # Prefix for a new log file
  prefix = "/var/hera/logs/hera-daemon"
  # only log level above which
  level = "debug"
}

# Daemon listen to network rpc
listen = {
  # Host address, "0.0.0.0" for all
  address = "0.0.0.0"
  # Listen port, usually 10093 for release, and 10094 for debug
  port = 10093
}

# Send heartbeat by udp broadcasting / set network interfaces
network = {
  # Interfaces to exclude)
  exclude_interfaces = (
    "eth_lan2",
    "eth_lan3",
    "eth_lan4",
    "eth_lan5",
    "eth_usb0",
    "lo",
    "wlan0",
    "docker0"
  )
}

# Upload store to servers
upload = { 
  # Dynamically find servers (by listening to server heartbeat)
  dynamic = false

  # Fixed servers
  servers = (
    {
      remark = "测试机1"
      protocol = "rsync"
      destination = "HDP1:"
    }
  )

  # Local disk mount point
  localdisk_mountpoint = "/media/root"
}