# Host Name
name = "Tron"

# Directory to store record files
data_directory = "/home/rize/wayz/hera/recorder/build/data"

# File of setting
setting_file = "/home/rize/wayz/hera/recorder/build/setting.json"

# Directory to search and load plugins
plugin_directory = {
  # Load device-plugins from
  device = "/home/rize/wayz/hera/recorder/build/device"
  # Load upload-plugins from
  upload = "/home/rize/wayz/hera/recorder/build/storage"
}

# Log file Mode
log = {
  # Prefix for a new log file
  prefix = "/home/rize/wayz/hera/recorder/build/log"
  # only log level above which
  level = "info"
}

# Daemon listen to network rpc
listen = {
  # Host address, "0.0.0.0" for all
  address = "0.0.0.0"
  # Listen port, usually 10093 for release, and 10094 for debug
  port = 10094
}

# Send heartbeat by udp broadcasting / set network interfaces
network = {
  # Interfaces to exclude)
  exclude_interfaces = (
    "lo"
  )
}

# Upload store to servers
upload = { 
  # Dynamically find servers (by listening to server heartbeat)
  dynamic = false

  # Fixed servers
  servers = (
    {
      remark = "高精NFS-Smb"
      protocol = "smb"
      destination = "smb://admini:wayz1234@192.168.1.203/share/SHARE"
    },
    {
      remark = "内网NFS测试文件夹"
      protocol = "nfs"
      destination = "172.2.0.231:mnt/data/wayz-nfs/users/lyu/nfstest"
    }
  )

  # Local disk mount point
  localdisk_mountpoint = "/mnt"
}