# Host Name
name = "Tron"

# Directory to store record files
data_directory = "/home/rize/Documents/Wayz/recorder/build18/data"

# File of setting
setting_file = "/home/rize/Documents/Wayz/recorder/build18/setting.json"

# Directory to search and load plugins
plugin_directory = {
  # Load device-plugins from
  device = "/home/rize/Documents/Wayz/recorder/build18/device"
  # Load upload-plugins from
  upload = "/home/rize/Documents/Wayz/recorder/build18/storage"
}

# Log file Mode
log = {
  # Prefix for a new log file
  prefix = "/home/rize/Documents/Wayz/recorder/build18/log"
  # only log level above which
  level = "info"
}

# Daemon listen to network rpc
listen = {
  # Host address, "0.0.0.0" for all
  address = "0.0.0.0"
  # Listen port, usually 10093 for release, and 10094 for debug
  port = 10094
}

# Send heartbeat by udp broadcasting
heartbeat = {
  # To 'include' / 'exclude' interfaces
  # include = true
  # exclude = false
  mode = false

  # Interfaces to use (or exclude)
  interfaces = ( )

  # Period [seconds]
  period = 5.0
}

# Upload store to servers
upload = { 
  # Dynamically find servers (by listening to server heartbeat)
  dynamic = false

  # Fixed servers
  servers = (
    {
      remark = "测试机1"
      protocol = "rsync"
      destination = "HDP1:"
    },
    {
      remark = "内网NFS测试文件夹"
      protocol = "nfs"
      destination = "172.2.0.231:mnt/data/wayz-nfs/users/lyu/nfstest"
    }
  )

  # Local disk mount point
  localdisk_mountpoint = "/mnt"
}