// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include <signal.h>
#include <unistd.h>

#include <common/logger/logger.hpp>
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/protocol/TJSONProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TBufferTransports.h>
#include <thrift/transport/THttpServer.h>
#include <thrift/transport/THttpTransport.h>
#include <thrift/transport/TServerSocket.h>

#include "tron_service_handler.hpp"

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;
using namespace ::wayz::tron;

TSimpleServer* g_server_ptr = nullptr;
TronServiceHandler* g_handler_ptr = nullptr;
void sig_int_handler_func(int s)
{
    if (g_server_ptr) {
        g_server_ptr->stop();
        g_handler_ptr->clear();
    }
    Logger::info() << "TronMain: Sigint Received, Stopping" << Logger::endl;
}

int main(int argc, char** argv)
{
    struct sigaction sig_int_handler;
    sig_int_handler.sa_handler = sig_int_handler_func;
    sigemptyset(&sig_int_handler.sa_mask);
    sig_int_handler.sa_flags = 0;
    sigaction(SIGINT, &sig_int_handler, NULL);

    Logger::create("logs");

    int port = 9090;
    std::shared_ptr<TronServiceHandler> handler(new TronServiceHandler());
    g_handler_ptr = handler.get();
    std::shared_ptr<TProcessor> processor(new TronServiceProcessor(handler));
    std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
    std::shared_ptr<TTransportFactory> transportFactory(new THttpServerTransportFactory());
    std::shared_ptr<TProtocolFactory> protocolFactory(new TJSONProtocolFactory());

    g_server_ptr = new TSimpleServer(processor, serverTransport, transportFactory, protocolFactory);
    Logger::info() << "TronMain: Daemon Started" << Logger::endl;
    g_server_ptr->serve();
    Logger::info() << "TronMain: Daemon Stoped" << Logger::endl;
    return 0;
}
