
///
/// @brief Generated by hera-parameter-generator
///
/// # 启用限制帧率功能
/// # 若开启, 相机将输出帧率限制到 FrameRate
/// # 否则, 每一帧都会被输出保存
/// mutable boolean SkipFrame = true;
/// 
/// # 限制后的相机帧率
/// mutable real FrameRate = 10.0; range 1.0, 20.0, 1.0
/// 
/// # 图像保存格式
/// # JPEG: JPEG压缩格式，其压缩质量由 JpegQuality 控制
/// # RGB8: RGB各8位，非压缩，每像素24位
/// mutable enum SaveFormat = JPEG; options JPEG, RGB8
/// 
/// # JPEG质量
/// # 控制 JPEG 图像质量的参数
/// # 该值越高则图像质量越好，相应地，图像数据大小也会增大
/// mutable integer JpegQuality = 90; range 0, 100, 5

#pragma once

#include "common/include/third_party/enum.hpp"
#include "device/include/parameter.hpp"

namespace wayz {
namespace hera {
namespace device {    
namespace camera {
namespace s32vsal {

BETTER_ENUM(SaveFormat, int32_t, JPEG, RGB8);

class LocalParameters : public ParametersInterface {
public:
    LocalParameters()
    {
        set_SkipFrame("true");
        set_FrameRate(10.0);
        set_SaveFormat("JPEG");
        set_JpegQuality(90);
    }

private:
    static bool m_to_bool(const std::string& str) {
        if (str.empty()) {
            return false;
        } else if (str[0] == 'F' || str[0] == 'f' || str[0] == '0') {
            return false;
        } else {
            return true;
        }
    } 

public:
    std::string rules() const override {
        return static_rules();
    }

    static std::string static_rules() {
        return R"RR([{"comment":"启用限制帧率功能\n若开启, 相机将输出帧率限制到 FrameRate\n否则, 每一帧都会被输出保存","defaultValue":"true","mutable":true,"name":"SkipFrame","requirement":"","type":"boolean"},{"comment":"限制后的相机帧率","defaultValue":"10.0","mutable":true,"name":"FrameRate","range":{"max":"20.0","min":"1.0","step":"1.0"},"requirement":"","type":"double"},{"comment":"图像保存格式\nJPEG: JPEG压缩格式，其压缩质量由 JpegQuality 控制\nRGB8: RGB各8位，非压缩，每像素24位","defaultValue":"JPEG","mutable":true,"name":"SaveFormat","options":["JPEG","RGB8"],"requirement":"","type":"enum"},{"comment":"JPEG质量\n控制 JPEG 图像质量的参数\n该值越高则图像质量越好，相应地，图像数据大小也会增大","defaultValue":"90","mutable":true,"name":"JpegQuality","range":{"max":"100","min":"0","step":"5"},"requirement":"","type":"int"}])RR";
    }

public:
    bool set(const nlohmann::json& json_input) override
    {
        bool good = true;
        good &= set_SkipFrame(json_input["SkipFrame"].get<std::string>());
        good &= set_FrameRate(json_input["FrameRate"].get<std::string>());
        good &= set_SaveFormat(json_input["SaveFormat"].get<std::string>());
        good &= set_JpegQuality(json_input["JpegQuality"].get<std::string>());

        return good;
    }

    bool set(const std::string& type, const std::string& value) override
    {
        if (type == "SkipFrame") { return set_SkipFrame(value);}
        if (type == "FrameRate") { return set_FrameRate(value);}
        if (type == "SaveFormat") { return set_SaveFormat(value);}
        if (type == "JpegQuality") { return set_JpegQuality(value);}
        return false;
    }

public:
    bool get_SkipFrame() const noexcept
    {
        return m_SkipFrame;
    }

    bool set_SkipFrame(const bool& value)
    {
        json_values_["SkipFrame"] = value;
        m_SkipFrame = value;
        return true;
    }

    bool set_SkipFrame(const std::string& value)
    {
        try {
            bool t_value = m_to_bool(value);
            set_SkipFrame(t_value);
            return true;
        } catch (std::exception& e) {
            return false;
        }
    }

private:
    bool m_SkipFrame{};

public:
    double get_FrameRate() const noexcept
    {
        return m_FrameRate;
    }

    bool set_FrameRate(const double& value)
    {
        json_values_["FrameRate"] = value;
        m_FrameRate = value;
        return true;
    }

    bool set_FrameRate(const std::string& value)
    {
        try {
            double t_value = std::stod(value);
            set_FrameRate(t_value);
            return true;
        } catch (std::exception& e) {
            return false;
        }
    }

private:
    double m_FrameRate{};

public:
    SaveFormat get_SaveFormat() const noexcept
    {
        return m_SaveFormat;
    }

    bool set_SaveFormat(const SaveFormat& value)
    {
        json_values_["SaveFormat"] = value._to_string();
        m_SaveFormat = value;
        return true;
    }

    bool set_SaveFormat(const std::string& value)
    {
        auto t_value = SaveFormat::_from_string_nocase_nothrow(value.c_str());
        if (t_value) {
            set_SaveFormat(*t_value);
            return true;
        } else {
            return false;
        }
    }

private:
    SaveFormat m_SaveFormat{SaveFormat::JPEG};


public:
    int get_JpegQuality() const noexcept
    {
        return m_JpegQuality;
    }

    bool set_JpegQuality(const int& value)
    {
        json_values_["JpegQuality"] = value;
        m_JpegQuality = value;
        return true;
    }

    bool set_JpegQuality(const std::string& value)
    {
        try {
            int t_value = std::stoll(value);
            set_JpegQuality(t_value);
            return true;
        } catch (std::exception& e) {
            return false;
        }
    }

private:
    int m_JpegQuality{};

};

}  // namespace camera
}  // namespace s32vsal
}  // namespace device
}  // namespace parameter
}  // namespace device
