
///
/// @brief Generated by hera-parameter-generator
///
/// # 主串口设备路径
/// # 获取 GNSS 报文的串口设备在系统中的路径
/// immutable string Primary = "/dev/tty"; regex ^\/(\w+\/?)+$
/// 
/// # 主串口设备波特率
/// immutable integer BaudPrimary = 115200; range 120, 256000, 1
/// 
/// # 同步板卡串口设备路径
/// # 获取同步信息的串口设备在系统中的路径
/// immutable string Auxiliary = "/dev/tty"; regex ^\/(\w+\/?)+$
/// 
/// # 同步板卡串口波特率
/// immutable integer BaudAux = 230400; range 120, 256000, 1
/// 
/// # 同步信息串口帧识别号
/// # 参考https://confluence.newayz.com/pages/viewpage.action?pageId=23200506
/// # 通常为1, 不需修改
/// immutable integer MsgType = 1; range 0, 7, 1

#pragma once

#include "common/include/third_party/enum.hpp"
#include "device/include/parameter.hpp"

namespace wayz {
namespace hera {
namespace device {    
namespace gnss {
namespace serialsync {

class LocalParameters : public ParametersInterface {
public:
    LocalParameters()
    {
        set_Primary("/dev/tty");
        set_BaudPrimary(115200);
        set_Auxiliary("/dev/tty");
        set_BaudAux(230400);
        set_MsgType(1);
    }

private:
    static bool m_to_bool(const std::string& str) {
        if (str.empty()) {
            return false;
        } else if (str[0] == 'F' || str[0] == 'f' || str[0] == '0') {
            return false;
        } else {
            return true;
        }
    } 

public:
    std::string rules() const override {
        return static_rules();
    }

    static std::string static_rules() {
        return R"RR([{"comment":"主串口设备路径\n获取 GNSS 报文的串口设备在系统中的路径","defaultValue":"/dev/tty","mutable":false,"name":"Primary","regex":"^\\/(\\w+\\/?)+$","requirement":"","type":"string"},{"comment":"主串口设备波特率","defaultValue":"115200","mutable":false,"name":"BaudPrimary","range":{"max":"256000","min":"120","step":"1"},"requirement":"","type":"int"},{"comment":"同步板卡串口设备路径\n获取同步信息的串口设备在系统中的路径","defaultValue":"/dev/tty","mutable":false,"name":"Auxiliary","regex":"^\\/(\\w+\\/?)+$","requirement":"","type":"string"},{"comment":"同步板卡串口波特率","defaultValue":"230400","mutable":false,"name":"BaudAux","range":{"max":"256000","min":"120","step":"1"},"requirement":"","type":"int"},{"comment":"同步信息串口帧识别号\n参考https://confluence.newayz.com/pages/viewpage.action?pageId=23200506\n通常为1, 不需修改","defaultValue":"1","mutable":false,"name":"MsgType","range":{"max":"7","min":"0","step":"1"},"requirement":"","type":"int"}])RR";
    }

public:
    bool set(const nlohmann::json& json_input) override
    {
        bool good = true;
        good &= set_Primary(json_input["Primary"].get<std::string>());
        good &= set_BaudPrimary(json_input["BaudPrimary"].get<std::string>());
        good &= set_Auxiliary(json_input["Auxiliary"].get<std::string>());
        good &= set_BaudAux(json_input["BaudAux"].get<std::string>());
        good &= set_MsgType(json_input["MsgType"].get<std::string>());

        return good;
    }

    bool set(const std::string& type, const std::string& value) override
    {
        if (type == "Primary") { return set_Primary(value);}
        if (type == "BaudPrimary") { return set_BaudPrimary(value);}
        if (type == "Auxiliary") { return set_Auxiliary(value);}
        if (type == "BaudAux") { return set_BaudAux(value);}
        if (type == "MsgType") { return set_MsgType(value);}
        return false;
    }

public:
    std::string get_Primary() const noexcept
    {
        return m_Primary;
    }

    bool set_Primary(const std::string& value)
    {
        json_values_["Primary"] = value;
        m_Primary = value;
        return true;
    }

private:
    std::string m_Primary{};

public:
    int get_BaudPrimary() const noexcept
    {
        return m_BaudPrimary;
    }

    bool set_BaudPrimary(const int& value)
    {
        json_values_["BaudPrimary"] = value;
        m_BaudPrimary = value;
        return true;
    }

    bool set_BaudPrimary(const std::string& value)
    {
        try {
            int t_value = std::stoll(value);
            set_BaudPrimary(t_value);
            return true;
        } catch (std::exception& e) {
            return false;
        }
    }

private:
    int m_BaudPrimary{};

public:
    std::string get_Auxiliary() const noexcept
    {
        return m_Auxiliary;
    }

    bool set_Auxiliary(const std::string& value)
    {
        json_values_["Auxiliary"] = value;
        m_Auxiliary = value;
        return true;
    }

private:
    std::string m_Auxiliary{};

public:
    int get_BaudAux() const noexcept
    {
        return m_BaudAux;
    }

    bool set_BaudAux(const int& value)
    {
        json_values_["BaudAux"] = value;
        m_BaudAux = value;
        return true;
    }

    bool set_BaudAux(const std::string& value)
    {
        try {
            int t_value = std::stoll(value);
            set_BaudAux(t_value);
            return true;
        } catch (std::exception& e) {
            return false;
        }
    }

private:
    int m_BaudAux{};

public:
    int get_MsgType() const noexcept
    {
        return m_MsgType;
    }

    bool set_MsgType(const int& value)
    {
        json_values_["MsgType"] = value;
        m_MsgType = value;
        return true;
    }

    bool set_MsgType(const std::string& value)
    {
        try {
            int t_value = std::stoll(value);
            set_MsgType(t_value);
            return true;
        } catch (std::exception& e) {
            return false;
        }
    }

private:
    int m_MsgType{};

};

}  // namespace gnss
}  // namespace serialsync
}  // namespace device
}  // namespace parameter
}  // namespace device
