///
/// @file foobar.hpp
/// @author zheming.lyu (zheming.lyu@wayz.ai)
/// @brief Header of class Foobar and class FoobarDeviceData
/// @version 0.1
/// @date 2019-11-07
///
/// @copyright Copyright 2018 Wayz.ai. All Rights Reserved.
///

#pragma once

#include "../../device.hpp"
#include "../dummy_data.hpp"

namespace wayz {
namespace hera {
namespace device {
namespace dummy {
namespace foobar {

#pragma pack(push, 1)

///
/// @brief Device data for dummy::Foobar, Derived from Storage Data
///
class FoobarData final : public data::DeviceData {
public:
    FoobarData() = delete;

public:
    ///
    /// @brief Data structure of dummy::Foobar packet
    ///
    /// The packet is generated by dummy code
    ///
    struct FoobarDataUnion {
        int32_t int_value;               ///< a dummy int value
        int8_t char_value[4];            ///< a dummy char array with fixed length
        uint32_t string_message_length;  ///< length of string_message
        uint8_t string_message[0];       ///< a variable-length buffer
    };

    ///
    /// @brief Union to allow access by data or by bytes
    ///
    union {
        FoobarDataUnion data;                  ///< union entry: data with structure
        uint8_t buf[sizeof(FoobarDataUnion)];  ///< union entry: raw buffer of bytes
    };
};

#pragma pack(pop)

///
/// @brief A dummy device foobar, for sample, Derived from Device
///
class Foobar final : public Device {
public:
    ///
    /// @brief Construct a new Velodyne object
    ///
    /// @note pass DummyRate and DummyValue as essential parameters
    /// @see Device::Device()
    Foobar(const uint32_t id,
           const std::string& vendor_type,
           const std::string& name,
           const bool forward,
           storage::StorageManager* const storage) :
        Device(id, vendor_type, name, forward, storage, HistoryDepth_, EssentialParameterTypes)
    {}
    Foobar(const Foobar&) = delete;
    Foobar& operator=(const Foobar&) = delete;

    ///
    /// @brief Destroy the Aceinna object
    ///
    /// calls Device::stop()
    virtual ~Foobar()
    {
        stop();
    }

    virtual HeraErrno connect() override;

    virtual void disconnect() override;

    virtual data::DeviceDataPtr fetch() override;

    virtual HeraErrno adjust_parameter(DeviceParameterType type, const std::string& value) override;

    virtual data::SensorDataPtr convert(data::DeviceDataPtr& storage_data) override
    {
        return do_convert(storage_data);
    }

    ///
    /// @brief Static convert function for read / convert / replay
    ///
    static data::SensorDataPtr do_convert(data::DeviceDataPtr& storage_data);

public:
    static const std::vector<DeviceParameterType> EssentialParameterTypes;  ///< Essential Parameters for device

    static const std::vector<DeviceParameterType> OptionalParameterTypes;  ///< Optional Parameters for device

private:
    static constexpr size_t HistoryDepth_ = 10;  ///< History Depth, 10

    int64_t period_us_;           ///< period on which dummy device return a new data, in us
    int32_t int_value_;           ///< the int value to fill device data
    std::string string_message_;  ///< the string message to fill device data

    static const std::string DefaultMessage_;  ///< Default value of string message
};

}  // namespace foobar
}  // namespace dummy
}  // namespace device
}  // namespace hera
}  // namespace wayz